# Server address to listen on
ServerAddress = "localhost:4000"
# Enable logging of server requests
UseLogger = true
# Logger output: "stdout" or "file"
LogOutput = "stdout"
# Log file path (used if LogOutput is "file")
LogFile = ""
# Colorize log output (only applies to stdout)
ColorizeLogger = true
# Enable HTTPS
UseTLS = false
# Path to SSL certificate file
CertFile = "cert.pem"
# Path to SSL key file
KeyFile = "key.pem"
# Use Let's Encrypt for SSL
UseAutoTLS = false
# Domain name for Let's Encrypt
Domain = "example.com"
# Cache directory for Let's Encrypt certificates
CacheDir = "/var/www/.cache"
# Enable Cross-Origin Resource Sharing (CORS)
EnableCORS = false
# Allowed origins for CORS
CORSAllowOrigins = ["https://example.com"]
# Allowed methods for CORS
CORSAllowMethods = ["GET", "PUT", "POST", "DELETE"]
# Maximum Rate Limit
RateLimit = 1000.0
# Maximum Rate Burst
RateBurst = 100

[Auth]
# Secret key for JWT token generation
JwtSecretKey = "your_secret_key_here"
# JWT token expiration time
JwtExpirationTime = "72h"

[Database]
# Database connection URL
Url = "postgres://user:password@localhost/db?sslmode=disable"
# Maximum number of open connections to the database
MaxConns = 10
# Maximum number of idle connections in the pool
MaxIdleConns = 5
# Maximum amount of time a connection may be reused
ConnMaxLifetime = "1h"

[StaticPaths]
# Paths for serving static files
css = "resources/css"
js = "resources/js"
images = "resources/images"

[State]
# Initial application state
InitialState = { user = "", isAuthenticated = false }

[TLS]
# Path to SSL certificate file
CertFile = "cert.pem"
# Path to SSL key file
KeyFile = "key.pem"
# Enable HTTPS
UseTLS = false
